apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubecounted-prometheus-stack
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: kubecounted
  endpoints:
  - port: web
    path: /metrics
